name: "Checkout Workspace Directory"
description: ""

inputs:
  CHECKOUT_BASE:
    required: false
    description: "Use 'true' to checkout the Base commits, and omit for Job commits"

runs:
  using: "composite"
  steps:
    - shell: bash
      working-directory: ${{ env.WORKDIR }}
      run: |
        make nuke CONFIRM=yes
        git clean -ffxd
        git reset --hard
        rm -rf _build
        commits=${{ inputs.CHECKOUT_BASE == 'true' && env.COMMITS_BASE || env.COMMITS_JOB }}
        ./dev/ci/checkout.sh ${{ env.SCRATCHDIR }}/$commits
        make describe | sort | tee desc.txt
        diff <(sort ${{ env.SCRATCHDIR }}/$commits) desc.txt
