name: "Prepare to Checkout Workspace Directory"
description: ""

inputs:
  FM_CI_TOKEN:
    required: true
    description: "secrets.FM_CI_TOKEN"
    type: string

runs:
  using: "composite"
  steps:
    # Use local version if changing workspace, otherwise checkout from main
    - uses: ./.github/actions/initialize_workspace
      if: github.repository == 'SkylabsAI/workspace'
      with:
        FM_CI_TOKEN: ${{ inputs.FM_CI_TOKEN }}
    - uses: SkylabsAI/workspace/.github/actions/initialize_workspace@main
      if: github.repository != 'SkylabsAI/workspace'
      with:
        FM_CI_TOKEN: ${{ inputs.FM_CI_TOKEN }}
    - uses: actions/download-artifact@v5
      with:
        name: "commit-files"
        path: ${{ env.SCRATCHDIR }}
