name: "Prepare to Checkout Workspace Directory"
description: "Invoked exactly once per job. Depends on 'Download CI files' step."

inputs:
  FM_CI_TOKEN:
    required: true
    description: "secrets.FM_CI_TOKEN"
    type: string

runs:
  using: "composite"
  steps:
    - uses: ./actions/initialize_workspace
      with:
        FM_CI_TOKEN: ${{ inputs.FM_CI_TOKEN }}
    - uses: actions/download-artifact@v5
      with:
        name: "commit-files"
        path: ${{ env.SCRATCHDIR }}
