name: "Prepare to Checkout Workspace Directory"
description: ""

inputs:
  FM_CI_TOKEN:
    required: true
    description: "secrets.FM_CI_TOKEN"
    type: string

runs:
  using: "composite"
  steps:
    # TODO branches here are a problem
    - uses: SkylabsAI/workspace/.github/actions/initialize_workspace@main
      with:
        FM_CI_TOKEN: ${{ inputs.FM_CI_TOKEN }}
    - uses: actions/download-artifact@v5
      with:
        name: "commit-files"
        path: ${{ env.SCRATCHDIR }}
