name: Filter

on:
  workflow_call:

jobs:
  Run-workspace:
    if: |
      ( github.repository == 'SkylabsAI/workspace' ) &&
      ( github.event_name == 'pull_request' ||
        ( github.event_name == 'push' &&
          github.ref_name == github.event.repository.default_branch ) ) &&
      !contains(github.event.pull_request.labels.*.name, 'ci-skip')
    # NOTE: Keep the previous line in sync with the `Skip` job below (modulo negation)
    uses: ./.github/workflows/main.yml
    secrets: inherit
  Run-elsewhere:
    if: |
      ( github.repository != 'SkylabsAI/workspace' ) &&
      ( github.event_name == 'pull_request' ||
        ( github.event_name == 'push' &&
          github.ref_name == github.event.repository.default_branch ) ) &&
      !contains(github.event.pull_request.labels.*.name, 'ci-skip')
    # NOTE: Keep the previous line in sync with the `Skip` job below (modulo negation)
    uses: SkylabsAI/workspace/.github/workflows/main.yml@main
    secrets: inherit
  Skip:
    name: "Skip CI?"
    # NOTE: Keep the next line in sync with the `Run` job above (modulo negation)
    if: contains(github.event.pull_request.labels.*.name, 'ci-skip')
    # We do not use our own runner to keep configuration to a minimum
    runs-on: ubuntu-latest
    steps:
      - id: skip-proofs
        name: "Skip Proofs?"
        shell: bash
        run: |
          echo "# Proofs skipped because of ci-skip label" >> $GITHUB_STEP_SUMMARY
          echo   "Proofs skipped because of ci-skip label"
          exit 1
